### ISSUE TITLE
Issue with custom getURLStem() methods

### ISSUE THREAD

**Issue by sebduggan** [blueriver/MuraTranslations#22]
I have a Mura install with several sites under it.

All the sites apart from the default site have a custom getURLStem() method in {siteid}/includes/contentRenderer.cfc.

This works fine when generating sitemaps manually with the respective site selected in the admin.

However, when the generate call is not made from the admin - e.g. when it's scheduled - the contentRenderer returned by getContentRenderer is the one for the default site, which doesn't have the custom method, and so the generated URLs are incorrect.

Is it possible to ensure that when calling the generation URL, the contentRenderer returned is the one for the siteid passed in the parameters?

**Comment by grantshepert** [comment]
Hey Seb, can you post the url string you are trying to use?

**Comment by sebduggan** [comment]
The URL is /plugins/MeldGoogleSitemaps/?action=process:&site=sitename

If you add a dump of the renderer object to the result page, you can see 
that if the call is made by clicking the "Generate Sitemap" button, the 
contentRenderer is the correct one for the site. But if it's just called 
directly, it uses the contentRenderer from the default site.


Grant Shepert wrote:

**Comment by sebduggan** [comment]
Hi Grant,

Slight clarification to what I previously claimed...

It's not necessarily the contentRenderer of the default site that will 
be used. Assuming that you have multiple sites with the same domain name 
(i.e. have the site name in the URL), it's the first site that Mura 
finds with that domain name that will be used.

For example, if you have 3 sites:

www.mydomain.com/en/
www.mydomain.com/fr/
www.mydomain.com/nl/

....then, if you access the sitemap generation page directly, it will 
always be the /en/ contentRenderer that is used.


Seb

> Seb Duggan <mailto:seb@sebduggan.com>
> 23 March 2015 23:42
> The URL is /plugins/MeldGoogleSitemaps/?action=process:&site=sitename
>
> If you add a dump of the renderer object to the result page, you can 
> see that if the call is made by clicking the "Generate Sitemap" 
> button, the contentRenderer is the correct one for the site. But if 
> it's just called directly, it uses the contentRenderer from the 
> default site.
>
>
> Grant Shepert wrote:
> Grant Shepert <mailto:notifications@github.com>
> 23 March 2015 15:18
>
> Hey Seb, can you post the url string you are trying to use?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/blueriver/MuraTranslations/issues/22#issuecomment-85045023>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by grantshepert** [comment]
I'm confused, Seb ... not sure this has anything to do with Mura Translations. Shouldn't this be under the Google Site Maps plugin? https://github.com/meldsolutions/Meld-Google-Sitemaps

**Comment by sebduggan** [comment]
Well, obviously it should :-)

Must have hit the wrong repository in GitHub...

Sorry for the confusion!

Grant Shepert wrote:
