### ISSUE TITLE
Mura Translations plugin import function doesn't work on Mura 6.2

### ISSUE THREAD

**Issue by JeffreyBouva** [blueriver/MuraTranslations#23]
Hi Guys,

I'm working on a multi-language website with Mura 6.2 and  when i'm running the import i will get an Javascript error from admin.min.js

```
Uncaught TypeError: Cannot read property 'value' of undefined     admin.min.js?coreversion=1:45 
```

Ik will drop some picture with this too! I really want to finish this website, is there anybody who can help me out?
![screen shot 2015-04-03 at 16 09 42](https://cloud.githubusercontent.com/assets/3510247/6983263/30431d56-da1c-11e4-8ed3-9096603b4a22.png)

![image 2015-04-03 at 4 10 01 pm](https://cloud.githubusercontent.com/assets/3510247/6983270/44f7f0be-da1c-11e4-9e36-7a74e89d92bb.png)

**Comment by CoenWarmer** [comment]
Has anyone found a fix for this yet?? We really need it for a project...
