### ISSUE TITLE
[Mura 7] configuration interface is not loading

### ISSUE THREAD

**Issue by Lagaffe** [blueriver/MuraTranslations#24]
The configuration interface doesn't work on Mura 7. Only the menu is shown but none of the tabs show their content.

**Comment by nsollecito** [comment]
Ditto.. Is there a documented process for updating plugins to work with the new Mura 7 UI?

**Comment by stevewithington** [comment]
@Lagaffe @nsollecito sorry guys, we're working on it and hope to have some info posted soon.

**Comment by nsollecito** [comment]
:+1:

**Comment by Tigerlady** [comment]
Hi Steve,  any news on the update to the plugin working on Mura 7.  Thanks.

**Comment by Lagaffe** [comment]
Is this issue fixed now that Mura7 has been released?

**Comment by Tigerlady** [comment]
I just downloaded the latest translation from GitHub and installed on a site that we are hoping to deploy in a few weeks.  When I go to the admin it doesn't show the content for the administration.  If I do a view source I see the code for the tabs but the actual content doesn't show up. We are currently running on 7.  Latest version.  I see there has been some recent updates but for some reason the tab content still doesnt' show through so we can manage it.

**Comment by Lagaffe** [comment]
I did some tests as well last Friday, issue isn't fixed yet.

**Comment by Tigerlady** [comment]
LaGaffe, Do you have any work around for this?  I am just hoping someone has been able to come up with a fix.

**Comment by stevewithington** [comment]
@Lagaffe @Tigerlady @nsollecito i've fixed the interface issue in my latest pull request. However, I've noticed a few other bugs with the plugin itself that we're currently looking in to. Thanks!
