### ISSUE TITLE
Possible bug, links to translation don't work properly, Mura 7 and Mura 6.2

### ISSUE THREAD

**Issue by bowler865** [blueriver/MuraTranslations#27]
I have a two sites, english and spanish, which I've upgraded to Mura 7 from 6.1.

In 6.1 the links between the sites to the pages work fine.

In 7 and 6.2, the links do not include the domain name so the links are not correct and result in 404 error.

I have www.company.com as the english site and es.company.com as the spanish site.

Links to the other language always starts with "/" instead of "http://www.company.com" or "http://es.company.com" depending on the language you are currently on.

I have updated my plugin on the Mura 7 and Mura 6.2 installations to make sure I have the latest version. Still no luck.

**Comment by bowler865** [comment]
Line 119 of translationManager.cfc updated to:

<cfreturn variables.$.createHREF( siteid=mapping.getRemoteSiteID(),filename=mapping.getFileName(),contentid=mapping.getRemoteID(),complete=1 )>

Added ,complete=1

Now the domain name is included with the URL to the translation.

**Comment by stevewithington** [comment]
@bowler865 thanks ... i've included the fix in the latest update.
