### ISSUE TITLE
Trying to get German site to show german urls not 404's

### ISSUE THREAD

**Issue by Tigerlady** [blueriver/MuraTranslations#37]
Steve,  I have started working on a new translation for a site for German.  Most of the issues and things I have tried are listed in this post on Google groups. https://groups.google.com/forum/#!topic/mura-cms-developers/Gy1PI5dh8QU

I have tried various version to get this to work but nothing is actually helping.  Maybe you have some insights that I just am not seeing.

Thank you.

**Comment by stevewithington** [comment]
Closing issue as it appears you had a rewrite issue. Feel free to reopen if I'm wrong. Thanks!
