### ISSUE TITLE
Mura Translations import function doesn't work in Mura 7

### ISSUE THREAD

**Issue by bowler865** [blueriver/MuraTranslations#38]
I'm attempting to create additional language sites by "Add Site" then import my English content (exported using Mura Translations Export function) into the new site.

In the help video, it shows this step as the way to auto-connect the pages between the languages.

The export from English seems to work fine, the .zip file is created and I downloaded it.

Then I create a site called "Italian", set the locale, name it, assign Mura Translations to the site, etc. Next I go to the External Translations tab of the Mura Translations plugin for the Italian site. Select my English export .zip file. Template is "default" just the same as the export. Under Content Staging Method I've tried Create New Change Set and Publish Immediately. Both have resulted in an error like the one below for every piece of content.

FAILED [PROCESSING]: about-us.about-the-founder.xml () Export report 11/05/2017 12:05:18

No content nodes are created in the new (Italian) site.

Mura 7.0.6890
ACF 10,0,21,30068
MySQL 5.5.5
Windows Server 2012 (6.2)

**Comment by grantshepert** [comment]
This should be fixed now.

**Comment by bowler865** [comment]
No, it's not. I just updated to the latest version of the same plugin, created a new site, imported the export of the english site into the blank test site. All the same errors on every single content node during the import process.
