### ISSUE TITLE
Content Render shows sites flagged as under development

### ISSUE THREAD

**Issue by Tigerlady** [blueriver/MuraTranslations#39]
We are just about ready to go live with our first translation of a site and have two other translations set as development mode.  When I add the display object to the page to show the translations those that are still in development mode flags are showing up.  Is there a way to turn off the flags if the sites are not in LIVE mode?  This is relatively urgent as they want to go live with the first one.  Hope someone has an answer.  

For example, the Spanish site is in development mode and I do not want the flag to show the content render for the Spanish site. 

![image](https://cloud.githubusercontent.com/assets/1850313/26471652/1f5f9d92-4168-11e7-9251-adcf6f28e604.png)

Thank you.

**Comment by Tigerlady** [comment]
I did get an answer to this from Scott,  

You could change line 43 of cfcs/translationManager.cfc to:

and tcontent.siteid != <cfqueryparam cfsqltype="cf_sql_varchar" value="#arguments.siteid#"> AND tsettings.enableLockdown != 'development'

However, this also affects the ability to assign translations pages in the admin.  Is there a way to turn it off for the front but have the translations available in the admin for assignments. 

For example, in the attached image I have a newly created Korean site and a Spanish site that are in Development mode because their translation isn't complete yet.  when I go to assign translation pages the Spanish doesn't show up in the Korean site and the Korean site doesn't show up in the Spanish.  

![image](https://user-images.githubusercontent.com/1850313/27097252-3d8a6452-5039-11e7-9f61-0c19d9fbc85b.png)

**Comment by grantshepert** [comment]
Sites not marked 'live' will no longer appear in navigation.
